baseURL = 'https://palstra.com/'
languageCode = 'en-us'
title = 'palstra.com'
[params]
  subtitle = 'Senior DevOps Engineer | Consultant | Trainer | Red Hat Certified OpenShift Architect | Rotterdam'
